<a href="https://colab.research.google.com/github/MamatkulovBunyodbek1999/Machine_Learning-a-quick-overview/blob/main/ML_2ndpart_Working_with_NaN_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science and artificial intelligence  Practikum

## 5-MODUL. Machine Learning

### 5.1 - steps of ML project 

# Machine Learning 
<img src="https://cdn-media-1.freecodecamp.org/images/1*92h6Lg1Bu1F9QqoVNrkLdQ.jpeg"
alt="California" width="600" height="350" />

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sklearn # scikit-learn library

In [ ]:
# Onlayn dataset joylashgan manzilini ko'rsatamiaz
URL = "https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.csv?raw=true"
df = pd.read_csv(URL)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

# Preparation for Machine Learning >>> NaN values.

## Let's split our data by following method >>>
```
train_test_split
```

In [ ]:
from sklearn.model_selection import train_test_split 
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42) 

In [ ]:
housing = train_set.drop(["median_house_value"], axis=1) #  I dropped Median_house_value column From train_set and created a new dataframe.
housing_labels = train_set["median_house_value"].copy()  # I got a copy from median_house_value. So Now  i have 2 new dataframes.

## We had some columns with NaN values, I will avoid them now. 
#### we have 2 options to do that. 1 st one is just to drop them, or we can fill the nan values.
```
fillna(), ffill(), bfill().
```

In [ ]:
median = housing["total_bedrooms"].median()
median

437.0

In [ ]:
housing["total_bedrooms"].fillna(median)


14196     627.0
8267      787.0
17445     331.0
14265     367.0
2271      431.0
          ...  
11284     201.0
11964     570.0
5390      569.0
860       597.0
15795    1315.0
Name: total_bedrooms, Length: 16512, dtype: float64

In [ ]:
housing["total_bedrooms"].isnull().sum() # I replaced NaN values with median values, as we can see our df does not have any NaNs now.

0

# Auto replacing technique ! Simple Imputer.
https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html

#### Just now we replaced NaN values just for one column. what if we have multiple columns with NaN ?. in this case we will need to make it outomatic, after which our each columns weill be filled outomatically

In [ ]:
from sklearn.impute import SimpleImputer # SimpleImputer is a Class.
imputer = SimpleImputer(strategy="median") # Creating an object.

In [ ]:
imputer.fit(housing) # If we run ths cell, it will give us traceback. Why ? Because our df has object column.

ValueError: ignored

In [ ]:
housing_num = housing.drop('ocean_proximity', axis=1) #  I've Created 

In [ ]:
housing_num.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542

## imputer.fit(df)

In [ ]:
imputer.fit(housing_num) # Nothing is executed, because it's just calculated median values. To see the result I will use another attribute called statistics_

SimpleImputer(strategy='median')

 ## imputer.statistics_
 ##### will just execute median arrays for each column. 

In [ ]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2129.    ,  437.    , 1167.    ,
        410.    ,    3.5458])

## imputer.transform(df)
#### It will fill each columns NaN values with median value, but will not affect our dataframe, it will just execute arrays which are filled with median values !!!!

In [ ]:
 X = imputer.transform(housing_num)
 X

array([[-1.1703e+02,  3.2710e+01,  3.3000e+01, ...,  2.3000e+03,
         6.2300e+02,  3.2596e+00],
       [-1.1816e+02,  3.3770e+01,  4.9000e+01, ...,  1.3140e+03,
         7.5600e+02,  3.8125e+00],
       [-1.2048e+02,  3.4660e+01,  4.0000e+00, ...,  9.1500e+02,
         3.3600e+02,  4.1563e+00],
       ...,
       [-1.1838e+02,  3.4030e+01,  3.6000e+01, ...,  1.7560e+03,
         5.2700e+02,  2.9344e+00],
       [-1.2196e+02,  3.7580e+01,  1.5000e+01, ...,  1.7770e+03,
         5.5900e+02,  5.7192e+00],
       [-1.2242e+02,  3.7770e+01,  5.2000e+01, ...,  2.6190e+03,
         1.2420e+03,  2.5755e+00]])

# imputer.fit_transform(df)
#### we can call "fit" and "Transform" methods at the same time.

In [ ]:
X = imputer.fit_transform(housing_num)

# Creating a dataframe from transformed X array

In [ ]:
housing_tr = pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)
housing_tr.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542

# SimpleEncoder 
#### Now it's time to work with object values"strings"

In [ ]:
#In our main housing dataframe we had object column called: "ocean_proximity"
#Now we will work on it.
housing_cat = housing[['ocean_proximity']] # Why cousing cat ? Because usually string columns often called catigorucal.

In [ ]:
housing_cat.head()

ocean_proximity
14196      NEAR OCEAN
8267       NEAR OCEAN
17445      NEAR OCEAN
14265      NEAR OCEAN
2271           INLAND

### As we can see that our df is consisted of strings, unfortunatelly our ML does not work with strings. THat's why we have to converte them into numbers.
# preprocessing >> OrdinalEncoder
```
from sklearn.preprocessing import OrdinalEncoder
```
<img src="https://e6v4p8w2.rocketcdn.me/wp-content/uploads/2022/01/One-Hot-Encoding-for-Scikit-Learn-in-Python-Explained-1024x576.png"
alt="California" width="600" height="350" />

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded[:10]

array([[4.],
       [4.],
       [4.],
       [4.],
       [1.],
       [0.],
       [0.],
       [3.],
       [0.],
       [0.]])

### Now we converted string column into integer ! But if we look at the original(string) column and our new arrays, it says that NEAR OCEAN equals 4, INLAND equals 0, and 1 HOUR TO OCEAN equals 1. But actually NEAR OCEAN and 1-HOUR TO OCEAN areas are very close to each other. But when we converted them into arrays, 4 and 0 are too far from each other. If INLAND=1, and 1 HOUR TO OCEAN=0, Then ML is gonna think that these areas are close to each other and gives us wrong predictions. To avoid this mistake, we can use >>>>>

# One Hot Encoder
<img src="https://e6v4p8w2.rocketcdn.me/wp-content/uploads/2022/01/One-Hot-Encoding-for-Scikit-Learn-in-Python-Explained-1024x576.png"
alt="California" width="600" height="350" />

In [ ]:
housing[['ocean_proximity']].head(10)

ocean_proximity
14196      NEAR OCEAN
8267       NEAR OCEAN
17445      NEAR OCEAN
14265      NEAR OCEAN
2271           INLAND
17848       <1H OCEAN
6252        <1H OCEAN
9389         NEAR BAY
6113        <1H OCEAN
6061        <1H OCEAN

#One Hot Encoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot.toarray()    


array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

# pd.get_dummies >>> same as onehotencoder but executes dataframe.

In [ ]:
housing_onehot = pd.get_dummies(housing["ocean_proximity"])
housing_onehot.head()

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
14196          0       0       0         0           1
8267           0       0       0         0           1
17445          0       0       0         0           1
14265          0       0       0         0           1
2271           0       1       0         0           0

# Building a transformer

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
# bizga kerak ustunlar indekslari
rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True):
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self # bizni funksiyamiz faqat transformer. estimator emas
    def transform(self, X):
        rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
        population_per_household = X[:, population_ix] / X[:, households_ix]
        if self.add_bedrooms_per_room: # add_bedrooms_per_room ustuni ixtiyoriy bo'ladi
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

In [ ]:
attr_adder = CombinedAttributesAdder() # new attribute adder from a new Transformer
housing_extra_attribs = attr_adder.transform(housing.values) # New numpy object

In [ ]:
housing.values[0,:]

array([-117.03, 32.71, 33.0, 3126.0, 627.0, 2300.0, 623.0, 3.2596,
       'NEAR OCEAN'], dtype=object)

In [ ]:
housing_extra_attribs[0,:]
                      

array([-117.03, 32.71, 33.0, 3126.0, 627.0, 2300.0, 623.0, 3.2596,
       'NEAR OCEAN', 5.017656500802568, 3.691813804173355,
       0.20057581573896352], dtype=object)

# Normalization. MinMaxScaler

# MinMaxScaler
<img src="https://pythonsimplified.com/wp-content/uploads/2022/06/MinMaxScaler.jpg?ezimgfmt=rs:372x139/rscb3/ng:webp/ngcb3"
alt="California" width="500" />

In [ ]:
housing_num.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542

#### All the numbers in our df has to be close to each other. Otherwise it will be a headache while making ML model. to do that MinMaxScaler will help us!

In [ ]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
min_max_scaler.fit_transform(housing_num) # all the numbers will be between (0-1)

array([[0.72908367, 0.01702128, 0.62745098, ..., 0.06437961, 0.10228581,
        0.19032151],
       [0.61653386, 0.12978723, 0.94117647, ..., 0.0367443 , 0.12415721,
        0.22845202],
       [0.38545817, 0.22446809, 0.05882353, ..., 0.02556125, 0.05508962,
        0.25216204],
       ...,
       [0.59462151, 0.15744681, 0.68627451, ..., 0.04913254, 0.08649893,
        0.16789424],
       [0.23804781, 0.53510638, 0.2745098 , ..., 0.04972112, 0.09176122,
        0.35994676],
       [0.19223108, 0.55531915, 1.        , ..., 0.07332044, 0.20407828,
        0.14314285]])

#StandardScaler /  Standartization
#### This method is not gonna make numbers between 0 and 1, but brings them much closer to each other.
<img src="https://miro.medium.com/max/1400/1*S_A58rURb7auyqciK6r-rw.jpeg"
alt="standartization" width="500" />

<img src="https://cdn-images-1.medium.com/max/370/1*Nlgc_wq2b-VfdawWX9MLWA.png"
alt="standartization" width="500" height="250"/>



In [ ]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
standard_scaler.fit_transform(housing_num)

array([[ 1.27258656, -1.3728112 ,  0.34849025, ...,  0.76827628,
         0.32290591, -0.326196  ],
       [ 0.70916212, -0.87669601,  1.61811813, ..., -0.09890135,
         0.6720272 , -0.03584338],
       [-0.44760309, -0.46014647, -1.95271028, ..., -0.44981806,
        -0.43046109,  0.14470145],
       ...,
       [ 0.59946887, -0.75500738,  0.58654547, ...,  0.28983345,
         0.07090859, -0.49697313],
       [-1.18553953,  0.90651045, -1.07984112, ...,  0.30830275,
         0.15490769,  0.96545045],
       [-1.41489815,  0.99543676,  1.85617335, ...,  1.04883375,
         1.94776365, -0.68544764]])